"""The city pages: one entry per place, the single source for every page
under /brand-strategy/ and for the cities block on the home page.

Started 5 October 2026 on Cydnie's brief: six local pages, the Strategy Day
($1,500) as the offer, a website or a Full Brand Launch as the next step,
linked from the home page and NOT from the navigation. Mane Alchemist Salon
is in Chisago and SRS Performance is in Minneapolis (her word); those two
pages carry the case. Every other page carries its own local reasoning, so
no two pages are the same page with a different town name on it (the
doorway-page risk recorded in HANDOFF 28).

THE FUTURE BLOG reads this file too. Each city lists `blog` topics: posts
written for that place, each linking back to its city page. Not built yet;
the slugs and URLs here are the contract it will link to, so do not rename
a slug without a redirect.

    python3 tools/gen_cities.py
"""

BASE = "/brand-strategy/"

CITIES = [
  {
    "slug": "forest-lake",
    "name": "Forest Lake",
    "place": "Forest Lake",                       # used in "in person in ___"
    "label": "Forest Lake, Minnesota",
    "short": "Home base",
    "title": "Brand Strategist in Forest Lake, MN | Cydnie Jocelyn",
    "description": "Brand strategy for Forest Lake small businesses from a strategist based in town. A $1,500 Strategy Day, then a website or full brand launch.",
    "h1": "Brand strategy for Forest Lake businesses, <em>from just down the road.</em>",
    "lede": "I&rsquo;m Cydnie Jocelyn, a brand and business strategist based right here in Forest Lake. In one Strategy Day we decide who your business is for, what it should be known for and what it says, and you leave with all of it in writing.",
    "img": ("cydnie-hero", "assets/img/cydnie-hero-%s.webp", (700, 1000, 1400), 1000, 1500,
            "Cydnie Jocelyn, brand and business strategist, smiling at her laptop in her studio"),
    "local_label": "Business in Forest Lake",
    "local_h2": "A town where people <em>already know your name.</em>",
    "local_p": [
      "Forest Lake is my home base, and business here runs on reputation. Most companies in town grew because someone told someone, and that works beautifully until you want to grow past the people who already know you.",
      "The next customer is someone who just moved up from the cities, a family at the lake for the summer, or an owner in Hugo or Scandia searching on a phone. They have never heard your story. Your brand has to tell it for you, and that starts with deciding what the story is.",
    ],
    "local_items": [
      ("Word of mouth that has gone quiet", "Referrals carried you this far. When they slow down, the brand has to do the introducing, and most local brands were never built to."),
      ("A website you have outgrown", "Built in a weekend when you opened, still describing the business you were then. The Strategy Day decides what the next one should say."),
      ("Doing every job yourself", "Owner run means you are the marketing, the sales and the service. Clear positioning means fewer things to explain, every single day."),
    ],
    "next_lede": "When a Forest Lake business is ready to be found by people who do not know it yet, the website is usually the next thing to build.",
    "proof": "quotes",
    "proof_label": "Close to home",
    "proof_h2": "Clients <em>up the road.</em>",
    "proof_lede": "Mane Alchemist Salon is a short drive up Highway 8 in Chisago. It started the way yours would: with a decision about what the business stands for, made before anything was designed. <a class=\"hv-inline\" href=\"/brand-strategy/chisago-city/\">See the Chisago work.</a>",
    "faq": [
      ("Do you meet in person in Forest Lake?",
       "Yes. Forest Lake is my home base, so a Strategy Day can be fully in person. Remote works just as well if that suits your week better."),
      ("How much does brand strategy cost in Forest Lake?",
       "A Strategy Day is $1,500 flat. Websites start at $4,000 and a Full Brand Launch starts at $15,000. Every price is published before you ever book a call."),
      ("Is this only for bigger businesses?",
       "No. Most of the businesses I work with are owner run: salons, studios, trades, practices and service firms. The day is built for the owner who makes every decision."),
      ("What if I just need a new website?",
       "Then the Strategy Day is the brief for it. A website built without positioning is a nicer looking version of the same problem. The day decides what the site has to say, and the build follows."),
    ],
    "close_h2": "Let&rsquo;s talk, <em>right here in town.</em>",
    "nearby": ["Hugo", "Scandia", "Wyoming", "Lino Lakes", "Columbus"],
    "area": [("City", "Forest Lake"), ("AdministrativeArea", "Washington County")],
    "blog": [
      "Why word of mouth stops working for Forest Lake businesses past a certain size",
      "What a Forest Lake small business website actually needs to say",
      "Lake season and the off season: building a brand for both",
    ],
  },
  {
    "slug": "minneapolis",
    "name": "Minneapolis",
    "place": "Minneapolis",
    "label": "Minneapolis, Minnesota",
    "short": "SRS Performance",
    "title": "Brand Strategist in Minneapolis, MN | Cydnie Jocelyn",
    "description": "Brand strategy for Minneapolis businesses in a crowded market. A $1,500 Strategy Day on positioning and message, then a website or full launch.",
    "h1": "Brand strategy for Minneapolis businesses <em>in a crowded market.</em>",
    "lede": "Minneapolis has no shortage of agencies. What it is short on is a partner who decides the positioning with you before anything gets designed. That is the Strategy Day: one day, and you leave with the decisions in writing.",
    "img": ("cydnie-direct", "assets/img/cydnie-direct-%s.webp", (600, 1000), 1000, 1500,
            "Cydnie Jocelyn smiling, a denim jacket slipping off one shoulder"),
    "local_label": "Business in Minneapolis",
    "local_h2": "When everyone is good, <em>specific wins.</em>",
    "local_p": [
      "In a city this size, your customer has a dozen good options within a few miles. Being good is the minimum. The business that gets chosen is the one that says exactly who it is for, so the right person recognizes themselves straight away.",
      "That is a positioning decision, not a design one, and it is the step most Minneapolis businesses skip on the way to a new logo. It is the first thing we do.",
    ],
    "local_items": [
      ("Sounding like everyone else", "If your website could swap names with a competitor&rsquo;s and nobody would notice, the problem is the message, not the colors."),
      ("Too broad to be remembered", "Serving everyone in the metro means nobody thinks of you first. Narrowing feels risky, and it is what makes you the first name someone thinks of."),
      ("Paying for design before decisions", "A rebrand without positioning is an expensive way to look different and say the same thing."),
    ],
    "next_lede": "In a market this competitive, the website is where the positioning gets tested against everyone else on the first page of a search.",
    "proof": "srs",
    "faq": [
      ("Do you work with Minneapolis businesses in person?",
       "Yes. I&rsquo;m based in Forest Lake, north of the cities, and I meet Minneapolis clients in person or remotely, whichever suits the work."),
      ("How is this different from hiring a Minneapolis branding agency?",
       "An agency hands you a project and moves on. I&rsquo;m one person across brand, operations and business development, and I stay in the work after launch. The Strategy Day is where that starts."),
      ("How much does brand strategy cost?",
       "A Strategy Day is $1,500, flat, with no hourly add-ons. If you go on to a website, that starts at $4,000, and a Full Brand Launch starts at $15,000."),
      ("Can you help with a rebrand?",
       "Yes, and a rebrand is where a Strategy Day matters most. We decide what has to change, and what has earned the right to stay, before anyone touches the logo."),
    ],
    "close_h2": "Ready to stop <em>blending in?</em>",
    "nearby": ["Northeast", "North Loop", "Uptown", "Edina", "Saint Louis Park"],
    "area": [("City", "Minneapolis"), ("AdministrativeArea", "Hennepin County")],
    "blog": [
      "How to stand out in a crowded Minneapolis market without shouting",
      "Positioning before the logo: what SRS Performance decided first",
      "Agency, freelancer or partner: hiring for brand work in Minneapolis",
    ],
  },
  {
    "slug": "saint-paul",
    "name": "Saint Paul",
    "place": "Saint Paul",
    "label": "Saint Paul, Minnesota",
    "short": "Neighborhood businesses",
    "title": "Brand Strategist in Saint Paul, MN | Cydnie Jocelyn",
    "description": "Brand strategy for Saint Paul neighborhood businesses. Put what your regulars love into words in a $1,500 Strategy Day, then build the website.",
    "h1": "Brand strategy for Saint Paul businesses <em>built on regulars.</em>",
    "lede": "The best Saint Paul businesses are built on people who keep coming back. A Strategy Day puts what your regulars already love about you into words, so new customers can find it too. One day, $1,500, everything in writing.",
    "img": ("cydnie-window", "assets/img/cydnie-window-%s.webp", (600, 1000), 1000, 1500,
            "Cydnie Jocelyn smiling by a sunlit window, one hand in her hair"),
    "local_label": "Business in Saint Paul",
    "local_h2": "A city of neighborhoods, <em>with long memories.</em>",
    "local_p": [
      "From Grand Avenue to Lowertown to West Seventh, Saint Paul is a city of neighborhoods, and the businesses that last here are the ones people feel belong to them.",
      "That loyalty is an asset most brands never write down. While it lives only in the owner&rsquo;s head, it cannot reach anyone new, and it does not survive a new hire, a second location or a website rebuild. Writing it down is the work of the day.",
    ],
    "local_items": [
      ("A brand that lives in your head", "Your regulars know exactly why you are different. Your website does not say it yet."),
      ("Growing past one location", "A second space or a new service line means the brand has to work without you standing in it."),
      ("An old site and loyal customers", "Regulars forgive a dated website. Someone searching from across the river will not."),
    ],
    "next_lede": "Once the reason people come back is written down, a website can say it to the people who have not found you yet.",
    "proof": "quotes",
    "proof_label": "In their words",
    "proof_h2": "What clients <em>say.</em>",
    "proof_lede": "The businesses I work with are owner run, like most of Saint Paul. Here is what two of them say about working together.",
    "faq": [
      ("Do you meet Saint Paul clients in person?",
       "Yes. I&rsquo;m in Forest Lake, north of the city, and I meet Saint Paul clients in person or remotely."),
      ("Will you change what my customers already love?",
       "No. The first half of the day is an audit of what is working and why, so the things your regulars come back for are named and protected before anything changes."),
      ("What does a Strategy Day cost?",
       "$1,500 flat. It is published, like every price on this site, and there are no hourly add-ons."),
      ("Do you build websites too?",
       "Yes. Websites start at $4,000, built in code and yours outright, and they are written from the decisions made in your Strategy Day."),
    ],
    "close_h2": "Let&rsquo;s put it <em>into words.</em>",
    "nearby": ["Roseville", "Shoreview", "Maplewood", "Woodbury", "West Saint Paul"],
    "area": [("City", "Saint Paul"), ("AdministrativeArea", "Ramsey County")],
    "blog": [
      "Turning neighborhood loyalty into a brand new customers can find",
      "Opening a second Saint Paul location without losing what made the first one work",
      "What your regulars know about your business that your website does not",
    ],
  },
  {
    "slug": "stillwater",
    "name": "Stillwater",
    "place": "Stillwater or White Bear Lake",
    "label": "Stillwater &amp; White Bear Lake",
    "short": "Main Street shops",
    "title": "Brand Strategist in Stillwater, MN | Cydnie Jocelyn",
    "description": "Brand strategy for Stillwater and White Bear Lake shops, salons and studios. A $1,500 Strategy Day, then a website that matches your storefront.",
    "h1": "Brand strategy for Stillwater and White Bear Lake <em>shops and studios.</em>",
    "lede": "A downtown business competes for a visitor&rsquo;s first five minutes and a neighbor&rsquo;s next ten years. A Strategy Day decides how your brand wins both, and you leave with it in writing.",
    "img": ("band-door", "assets/img/home/band-door-%s.webp", (700, 1100), 1100, 1375,
            "Cydnie Jocelyn laughing with a hand in her hair in front of an arched wooden door"),
    "local_label": "Business on Main Street",
    "local_h2": "Two kinds of customer, <em>one brand.</em>",
    "local_p": [
      "Downtown Stillwater on the St. Croix and downtown White Bear Lake are full of independent shops, salons, galleries and studios, and most of them serve two audiences: the weekend visitor deciding where to walk in, and the neighbor deciding where to come back.",
      "The visitor usually finds you on a phone before they find your door. The neighbor needs a reason to choose you over the shop next door. A brand that speaks to both on purpose is a positioning decision, and it is what the Strategy Day is for.",
    ],
    "local_items": [
      ("Beautiful in person, lost online", "Your storefront is lovely. If your website does not match it, the visitor searching from the coffee shop walks somewhere else."),
      ("Busy summers, quiet winters", "When the visitors go home, the brand has to bring the locals back."),
      ("Premium inside, ordinary online", "If the experience is premium, every touchpoint has to say so before the customer reaches the counter."),
    ],
    "next_lede": "For a downtown business, the website is the storefront people see first, so it is usually the next thing to build.",
    "proof": "quotes",
    "proof_label": "Client work",
    "proof_h2": "Positioning first, <em>then the look.</em>",
    "proof_lede": "Mane Alchemist Salon faced the question many downtown businesses do: how to look and feel as premium as the experience inside. It was positioned toward deliberate luxury first, and the identity followed. <a class=\"hv-inline\" href=\"/the-build/#work\">See the work.</a>",
    "faq": [
      ("Do you meet in person in Stillwater or White Bear Lake?",
       "Yes. Both are a short drive from my base in Forest Lake, so a Strategy Day can be in person or remote."),
      ("Is a Strategy Day worth it for a small shop?",
       "It is built for one. A small business has the least room for a brand that says the wrong thing, and $1,500 for the decisions costs less than a website built on a guess."),
      ("Can you help people find us on Google?",
       "Yes, as part of a website. Every site I build includes the copy and search foundations, so the people looking for what you sell can find you."),
      ("How much does it cost?",
       "A Strategy Day is $1,500 flat. Websites start at $4,000, and a Full Brand Launch starts at $15,000."),
    ],
    "close_h2": "Let&rsquo;s make the website <em>match the storefront.</em>",
    "nearby": ["Stillwater", "White Bear Lake", "Bayport", "Mahtomedi", "Hugo"],
    "area": [("City", "Stillwater"), ("City", "White Bear Lake"), ("AdministrativeArea", "Washington County")],
    "blog": [
      "Branding a Stillwater shop for visitors and locals at the same time",
      "Why your downtown storefront and your website should feel like the same place",
      "Getting through a quiet winter on Main Street: a brand that brings locals back",
    ],
  },
  {
    "slug": "blaine",
    "name": "Blaine",
    "place": "Blaine or Anoka County",
    "label": "Blaine &amp; Anoka County",
    "short": "Growing businesses",
    "title": "Brand Strategist in Blaine &amp; Anoka County | Cydnie Jocelyn",
    "description": "Brand strategy for growing Blaine and Anoka County businesses. One $1,500 Strategy Day decides who you serve and what you say, then the website.",
    "h1": "Brand strategy for Blaine and Anoka County <em>businesses that are growing.</em>",
    "lede": "Growth exposes everything a brand never decided. A Strategy Day decides it: who you serve, what you are known for and what you say, in one day and in writing.",
    "img": ("cydnie-writing", "assets/img/cydnie-writing-%s.webp", (600, 1000), 1000, 1500,
            "Cydnie Jocelyn sitting with an open notebook on her lap, writing"),
    "local_label": "Business in Anoka County",
    "local_h2": "Busy is not <em>the same as clear.</em>",
    "local_p": [
      "Blaine, Lino Lakes, Anoka, Ramsey and East Bethel are full of businesses that grew on hard work: contractors, clinics, studios, trades and service firms with more demand than time.",
      "Fast growth tends to leave the brand behind. The truck says one thing, the website another, and the owner explains the difference on every call. A Strategy Day puts one clear answer in place, so the business can keep growing without you repeating yourself.",
    ],
    "local_items": [
      ("Outgrowing the startup look", "The logo from year one did its job. Now it tells bigger clients you are smaller than you are."),
      ("Every job by referral", "Wonderful in year three. Fragile in year ten. A clear brand gives you a second way in."),
      ("Hiring before the story is written", "A new team member cannot explain the business the way you do unless it is written down."),
    ],
    "next_lede": "For a growing service business, the website is where a stranger decides whether you are worth a call, so it is usually the next thing to build.",
    "proof": "quotes",
    "proof_label": "In their words",
    "proof_h2": "Clear, <em>then growing.</em>",
    "proof_lede": "SRS Performance narrowed from general fitness to former competitive athletes, and redesigned how the business runs. That is what growth looks like once the brand is decided. <a class=\"hv-inline\" href=\"/brand-strategy/minneapolis/\">Read about SRS.</a>",
    "faq": [
      ("Do you work with trades and service businesses?",
       "Yes. Positioning matters just as much for a contractor or a clinic as it does for a boutique, and often more, because the customer is comparing quotes."),
      ("Do you meet in person in Blaine?",
       "Yes. Blaine and the rest of Anoka County are a short drive from Forest Lake, so a Strategy Day can be in person or remote."),
      ("What do I have at the end of the day?",
       "Your positioning and your message, in writing: who the business is for, what it is known for and the words to say it. It becomes the brief for your website or brand launch."),
      ("What does it cost?",
       "$1,500 flat for the Strategy Day. Websites start at $4,000 and a Full Brand Launch starts at $15,000, all published."),
    ],
    "close_h2": "Let&rsquo;s give the growth <em>a clear brand.</em>",
    "nearby": ["Blaine", "Lino Lakes", "Anoka", "Ramsey", "East Bethel"],
    "area": [("City", "Blaine"), ("AdministrativeArea", "Anoka County")],
    "blog": [
      "When a growing Blaine business outgrows its first logo",
      "Branding for contractors and service firms: winning when customers compare quotes",
      "Writing the story down before you hire: a guide for Anoka County owners",
    ],
  },
  {
    "slug": "chisago-city",
    "name": "Chisago City",
    "place": "Chisago County",
    "label": "Chisago City &amp; Chisago County",
    "short": "Mane Alchemist Salon",
    "title": "Brand Strategist in Chisago City, MN | Cydnie Jocelyn",
    "description": "Brand strategy for Chisago City and Chisago County businesses, from the strategist behind Mane Alchemist Salon. A $1,500 Strategy Day, then build.",
    "h1": "Brand strategy for Chisago County businesses <em>ready to be known.</em>",
    "lede": "Mane Alchemist Salon, here in Chisago, started with a decision before a design. A Strategy Day is where that decision gets made for your business: one day, $1,500, everything in writing.",
    "img": ("band-garden", "assets/img/home/band-garden-%s.webp", (700, 1100), 1100, 1375,
            "Cydnie Jocelyn smiling in a garden"),
    "local_label": "Business in Chisago County",
    "local_h2": "Small towns, <em>big reputations.</em>",
    "local_p": [
      "Chisago City, Lindstrom, Center City, North Branch and Taylors Falls are lake and river towns where a business can be known by everyone in town and invisible to everyone outside it.",
      "Growing here usually means reaching past the county line, to people driving up from the cities or searching from the next town over. That takes a brand that can do the introducing, and it starts with deciding what you want to be known for.",
    ],
    "local_items": [
      ("Known in town, invisible online", "Everyone here knows you. Someone searching from Forest Lake or the cities has to find you, and see the same business your neighbors do."),
      ("The safe choice, not the obvious one", "In a small town it is easy to become the default. Deliberate positioning makes you the first choice instead."),
      ("Pricing for the experience", "If what you offer is premium, the brand has to say so before the first appointment."),
    ],
    "next_lede": "Mane Alchemist went from one positioning decision to a full brand launch. Other businesses start with the website.",
    "proof": "mane",
    "faq": [
      ("Do you work with businesses in Chisago County?",
       "Yes. Mane Alchemist Salon in Chisago is one of my full brand launches, and the county is a short drive from my base in Forest Lake. A Strategy Day can be in person or remote."),
      ("What did Mane Alchemist Salon get?",
       "A Full Brand Launch: logo, brand guide and voice, a website, a 90-day social launch and quarterly content, all built from one positioning decision made first."),
      ("How much does a Strategy Day cost?",
       "$1,500 flat. If you go on to a full brand launch like Mane Alchemist&rsquo;s, that starts at $15,000, and websites start at $4,000."),
      ("Can I start with just the Strategy Day?",
       "Yes. The day stands on its own: you leave with your positioning and message in writing, and then you decide what to build."),
    ],
    "close_h2": "Let&rsquo;s decide what you&rsquo;ll be <em>known for.</em>",
    "nearby": ["Chisago City", "Lindstrom", "Center City", "North Branch", "Taylors Falls"],
    "area": [("City", "Chisago City"), ("AdministrativeArea", "Chisago County")],
    "blog": [
      "Known in town, invisible online: branding for Chisago County businesses",
      "How Mane Alchemist Salon was positioned toward deliberate luxury",
      "Reaching past the county line: being found from the cities",
    ],
  },
]


def url(c):
    return BASE + c["slug"] + "/"
