"""The shared frame for every page rebuilt on the 2026 luxury system.

Each rebuilt page is generated by a small script (tools/gen_<page>.py) that
supplies only what is its own: the head copy, the structured data, the FAQ
and the <main>. Everything shared -- the header, the footer, the icon sprite
with the vector wordmark, the menu and reveal scripts -- is lifted from the
home page, so a change there reaches every rebuilt page on the next run.

Edit a page's generator, never its output: the next run overwrites it.
Started 25 September 2026 (HANDOFF 71 onward). Work with me predates this
module and still has its own copy of the same logic in gen_work_with_me.py.
"""
import html as _html, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://www.cydniejocelyn.com"
CALL = "https://clients.cydniejocelyn.com/schedule/69f9f2a095c611cc2401eec7"    # free 30-min call
SOUND = "https://clients.cydniejocelyn.com/schedule/6a185c26693e14802690e9f6"   # The Sounding, $300
ARW = ('<svg viewBox="0 0 16 10" fill="none" aria-hidden="true"><path d="M11 1l4 4-4 4M15 5H0" '
       'stroke="currentColor" stroke-width="1.2"/></svg>')


def _between(s, a, b, incl=True):
    i = s.index(a)
    j = s.index(b, i) + (len(b) if incl else 0)
    return s[i:j]


def _home():
    return open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()


def shared(depth, active=None):
    """Header, footer, sprite, scripts and the lux.css stamp, re-pathed for
    a page `depth` folders below the root, with `active` marked current."""
    home = _home()
    pre = "../" * depth

    def up(s):
        return (s.replace('src="assets/', 'src="%sassets/' % pre)
                 .replace('href="assets/', 'href="%sassets/' % pre)
                 .replace(' assets/img', ' %sassets/img' % pre))

    header = up(_between(home, '<header class="hv-hdr"', '</header>'))
    if active:
        a = '<a href="%s">' % active
        if a in header:
            header = header.replace(a, '<a href="%s" aria-current="page">' % active, 1)
    return {
        "sprite": _between(home, '<svg width="0" height="0" style="position:absolute"', '</svg>'),
        "header": header,
        "footer": up(_between(home, '<footer class="hv-ftr">', '</footer>')),
        "scripts": up(_between(home, '<script>\n(function () {\n  var hdr', '</body>', incl=False)),
        "stamp": re.search(r'lux\.css\?v=([0-9a-f]+)', home).group(1),
        "pre": pre,
    }


def faq_html(faq):
    return "\n".join('      <details><summary>%s</summary><p>%s</p></details>'
                     % (q, a.replace("'", "&rsquo;")) for q, a in faq)


def faq_node(page_url, faq):
    return {"@type": "FAQPage", "@id": page_url + "#faq",
            "mainEntity": [{"@type": "Question", "name": _html.unescape(q),
                            "acceptedAnswer": {"@type": "Answer", "text": _html.unescape(a)}} for q, a in faq]}


def render(out, depth, active, title, description, canonical, og_title, og_description,
           graph, main, reveal=(), reveal_imgs=(), preload="", body_class="", og_image="home-2026.png",
           robots_html=None, canonical_html=None, head_extra=""):
    """robots_html / canonical_html replace the default robots meta and
    canonical link (a hidden page such as Arizona before launch passes its
    noindex pair and a commented canonical). head_extra goes after the
    JSON-LD, e.g. a parked block the launch script turns on."""
    sh = shared(depth, active)
    pre = sh["pre"]
    scripts = sh["scripts"]
    if reveal:
        scripts = scripts.replace("var groups = [", "var groups = [%s, " % ", ".join('"%s"' % r for r in reveal), 1)
    if reveal_imgs:
        scripts = scripts.replace("var imgs = [", "var imgs = [%s, " % ", ".join('"%s"' % r for r in reveal_imgs), 1)
    esc = lambda t: t.replace("&", "&amp;").replace("&amp;amp;", "&amp;")
    page = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">

<!-- Generated by tools/%(gen)s through tools/lux_page.py. Edit the
     generator, not this file. -->
<title>%(title)s</title>
<meta name="description" content="%(description)s">
%(robots_html)s
%(canonical_html)s
<meta name="author" content="Cydnie Jocelyn Brown">
<meta name="theme-color" content="#FFFFFF">
<meta name="geo.region" content="US-MN">
<meta name="geo.placename" content="Forest Lake, Minnesota">

<meta property="og:type" content="website">
<meta property="og:site_name" content="Cydnie Jocelyn">
<meta property="og:url" content="%(canonical)s">
<meta property="og:title" content="%(og_title)s">
<meta property="og:description" content="%(og_description)s">
<meta property="og:image" content="%(og_image)s">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="%(og_title)s">
<meta name="twitter:description" content="%(og_description)s">
<meta name="twitter:image" content="%(og_image)s">

<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="%(pre)sassets/img/cj-icon-32.png">
<link rel="icon" type="image/png" sizes="16x16" href="%(pre)sassets/img/cj-icon-16.png">
<link rel="apple-touch-icon" href="%(pre)sassets/img/cj-apple-180.png">
<link rel="manifest" href="/site.webmanifest">
%(preload)s<link rel="preload" href="/assets/fonts/instrument-sans-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/instrument-serif-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="%(pre)sassets/css/site.css?v=%(stamp)s">
<link rel="stylesheet" href="%(pre)sassets/css/lux.css?v=%(stamp)s">
<script>document.documentElement.className += " js-motion";</script>
<script type="application/ld+json">
%(jsonld)s
</script>
%(head_extra)s</head>

<body class="hv2%(body_class)s">
<a class="skip" href="#main">Skip to content</a>

%(sprite)s

%(header)s

%(main)s

%(footer)s

%(scripts)s</body>
</html>
""" % {
        "gen": "gen_" + os.path.basename(os.path.dirname(out)).replace("-", "_") + ".py",
        "title": esc(title), "description": esc(description), "canonical": canonical,
        "og_title": esc(og_title), "og_description": esc(og_description), "site": SITE,
        "og_image": og_image if og_image.startswith("http") else SITE + "/assets/og/" + og_image, "pre": pre, "preload": preload, "stamp": sh["stamp"],
        "jsonld": json.dumps({"@context": "https://schema.org", "@graph": graph}, indent=2, ensure_ascii=False),
        "body_class": (" " + body_class) if body_class else "",
        "robots_html": robots_html or '<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large">',
        "canonical_html": canonical_html if canonical_html is not None else '<link rel="canonical" href="%s">' % canonical,
        "head_extra": head_extra,
        "sprite": sh["sprite"], "header": sh["header"], "main": main.strip("\n"),
        "footer": sh["footer"], "scripts": scripts,
    }
    open(os.path.join(ROOT, out), "w", encoding="utf-8").write(page)
    return len(page)


def old_graph(path):
    """The structured data already on a page, as a list of nodes."""
    s = open(os.path.join(ROOT, path), encoding="utf-8").read()
    m = re.search(r'<script type="application/ld\+json">(.*?)</script>', s, re.S)
    d = json.loads(m.group(1))
    return d.get("@graph", [d])
